# Simple workflow for PRs in GitHub
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Add additional jobs here!!

  html-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install html-validate
        run: npm install -g html-validate
      - name: Run HTML validation
        run: |
          html-validate "**/*.html"
        continue-on-error: true

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Stylelint
        uses: actions-hub/stylelint@master
        env:
          PATTERN: "**/*.css"  # Define the pattern for stylelint to look for CSS files
        continue-on-error: true

  broken-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.2
        with:
          url: "https://ssd-group-project-4.github.io/EnterpriseSystemsAccessPortal/index.html"
          honorRobotExclusions: false
          recursiveLinks: false
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
        continue-on-error: true

  minify-html-css-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.1.0
        with:
          directory: '.'      
          output: '.'   
          add_suffix: false    
          inclusions: |-       
            .*css/.*\.css       
            .*js/.*\.js         
            .*\.html            
          exclusions: |-       
              .*playbooks/.*      
              .*icons/.* 
        # Log the minified file sizes
      - name: Show File Sizes after Minification
        run: |
          echo "File sizes of CSS files:"
          du -h css/ || echo "No CSS files found"
          echo "File sizes of JS files:"
          du -h js/ || echo "No JS files found"
          echo "File sizes of HTML files:"
          du -h *.html || echo "No HTML files found"
        continue-on-error: true  


  workflow-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Perform CodeQL Analysis
        uses: rcowsill/workflow-scan-action@v3 
        continue-on-error: true

  # End additional job steps!!
