# Simple workflow for PRs in GitHub
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Add additional jobs here!!

  html-validate-minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install html-validate
        run: npm install -g html-validate
      - name: Run HTML validation
        run: |
          html-validate "**/*.html"
        continue-on-error: true

      - name: HTML/CSS/JS Minifier
        uses: docker://devatherock/minify-js:3.1.0
        with:
          directory: '.'      
          output: 'minified'   
          add_suffix: false    
          inclusions: |-       
            .*css/.*\.css       
            .*js/.*\.js         
            .*\.html            
          exclusions: |-       
              .*playbooks/.*      
              .*icons/.* 
        # Log the output directory contents
      - name: List Minified Files
        run: |
          echo "Minified files:"
          ls -R minified

      # Log file size reductions
      - name: Show File Sizes Before and After Minification
        run: |
          echo "Original file sizes:"
          du -h css/ js/ *.html
          echo "Minified file sizes:"
          du -h minified          

  broken-link-check:
    runs-on: ubuntu-latest
    needs: html-validate-minify
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Run MkDocs server
        run: mkdocs serve -a 0.0.0.0:4444 &
        continue-on-error: true

      - name: Wait for server to start
        run: sleep 10

      - name: Run Link Checker
        uses: merlos/broken-links@0.2.2
        with:
          url: 'https://ssd-group-project-4.github.io/EnterpriseSystemsAccessPortal/index.html'
          only-errors: 'true'
          ignore-file: './check-ignore'
        continue-on-error: true


  # End additional job steps!!
