# Simple workflow for PRs in GitHub
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Add additional jobs here!!
  
  # End additional job steps!!
  html-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install html-validate
        run: npm install -g html-validate
      - name: Run HTML validation
        run: |
          html-validate "**/*.html"
        continue-on-error: true
  # Add CSS linting job here
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: stylelint
        uses: actions-hub/stylelint@master
        continue-on-error: true
